# Site wide configuration
#theme: jekyll-theme-minimal
title: Xiangrong Wang (王向荣)
locale: en_US
description: Shenzhen University
  
owner:
  name: Xiangrong Wang
  bio: "Shenzhen University."
  email: xiangrongwang88@gmail.com
  avatar: xiangrong.jpeg

#theme: jekyll-theme-leap-day
