# Site wide configuration
#theme: jekyll-theme-minimal
title: Xiangrong Wang (王向荣)
locale: en_US
description: Southern University of Science and Technology
  
owner:
  name: Xiangrong Wang
  bio: "Southern University of Science and Technology."
  email: xiangrongwang88@gmail.com
  avatar: xiangrong.jpeg

#theme: jekyll-theme-leap-day
